import XCTest
@testable import WispritPolish

/// Golden parity for the leaked-self-commentary stripper.
///
/// `PolishGuards.sanitize` is a port of `wisprit/polish.py`'s `_sanitize`, so
/// the expectations below are not hand-written: every pair was produced by
/// running the REAL Python (`~/.meetingscribe/venv/bin/python`) over the input
/// list and printing `_sanitize(input)`.
///
///     scratchpad/gen_sanitize_golden.py  (input corpus, incl. all nine cases
///                                         from tests/test_polish.py verbatim)
///     scratchpad/gen_sanitize_swift.py   (emits the literals below)
///
/// The extra cases past the ported nine pin the porting hazards specifically:
/// Python `len()` counting code points (Swift's `String.count` counts graphemes,
/// so the port uses `unicodeScalars.count`), `str.split("\n\n")` on a run of
/// three newlines, `re.match` being position-anchored, `re.sub(count=1)`
/// applying only at offset 0, the unconditional ASCII-quote unwrap (it does NOT
/// check for inner quotes), and the never-strip-everything floor.
final class SanitizeGoldenTests: XCTestCase {

    /// Generated by: gen_sanitize_swift.py
    static let goldens: [(String, String)] = [
        ("So I was gonna go to the store.",
         "So I was gonna go to the store."),
        ("The store, and grab milk.\n\nWait — that's wrong. Let me give the correct output:\n\nI was going to the store to grab milk.",
         "I was going to the store to grab milk."),
        ("The presentation deck is ready.\n\nActually, cleaned directly: Hi Bob, the deck is ready. When can you meet?",
         "Hi Bob, the deck is ready. When can you meet?"),
        ("Actually, cleaned directly: Hi Bob, the deck is ready.",
         "Hi Bob, the deck is ready."),
        ("Hello,\n\nPlease wait for the report.\n\nThank you.",
         "Hello,\n\nPlease wait for the report.\n\nThank you."),
        ("Actually, the meeting is at 3: everyone should attend.",
         "Actually, the meeting is at 3: everyone should attend."),
        ("Here's the corrected version:\n\nThe final text.",
         "The final text."),
        ("\"just a quoted line\"",
         "just a quoted line"),
        ("",
         ""),
        ("   padded on both sides   ",
         "padded on both sides"),
        ("'single quoted'",
         "single quoted"),
        ("\"an \"inner\" quoted line\"",
         "an \"inner\" quoted line"),
        ("\"unbalanced quote",
         "\"unbalanced quote"),
        ("I apologize for the confusion.\n\nThe deck is ready.",
         "The deck is ready."),
        ("My apologies, that is wrong.\n\nLet me rewrite:\n\nThe deck is ready, and the numbers are final.",
         "The deck is ready, and the numbers are final."),
        ("Let me give you some background: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx and that is the whole story.",
         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx and that is the whole story."),
        ("Let me redo that.",
         "Let me redo that."),
        ("Here is the cleaned text:",
         "Here is the cleaned text:"),
        ("Note: the meeting moved.",
         "Note: the meeting moved."),
        ("Summary: we shipped it.",
         "Summary: we shipped it."),
        ("output:no space after colon",
         "output:no space after colon"),
        ("output: spaced answer",
         "spaced answer"),
        ("Here's the corrected version:\n\nLine one.\nLine two.\n\nLine three.",
         "Line one.\nLine two.\n\nLine three."),
        ("Let me rewrite:\n\n\nThe answer.",
         "The answer."),
        ("こんにちは、世界。",
         "こんにちは、世界。"),
        ("Let me rewrite:\n\nこんにちは、世界。",
         "こんにちは、世界。"),
        ("\tLet me correct that:\t\n\nDone.",
         "Done."),
        ("Dear team,\n\nThe report is attached and I apologize for the delay in sending it out to everyone; the numbers took longer than expected to reconcile across the three regions.\n\nBest,\nSharique",
         "Dear team,\n\nThe report is attached and I apologize for the delay in sending it out to everyone; the numbers took longer than expected to reconcile across the three regions.\n\nBest,\nSharique"),
    ]

    func testSanitizeMatchesPython() {
        for (input, expected) in Self.goldens {
            XCTAssertEqual(PolishGuards.sanitize(input), expected,
                           "sanitize(\(input.debugDescription))")
        }
    }

    /// Sanitizing an already-sanitized string must be a no-op, or the
    /// `launder` composition (strip → sanitize → strip) could keep eating text.
    func testSanitizeIsIdempotent() {
        for (input, expected) in Self.goldens {
            _ = input
            XCTAssertEqual(PolishGuards.sanitize(expected), expected,
                           "sanitize is not idempotent for \(expected.debugDescription)")
        }
    }
}
