// GENERATED — do not hand-edit. Regenerate with:
//   ~/.meetingscribe/venv/bin/python pp_fuzz.py > Tests/WispritPostProcessTests/FuzzGoldens.swift
// 400 pseudo-random token salads (seed 20260805) over the vocabulary every
// stage's regexes react to, each paired with the real Python output. This is
// the differential net for ICU-vs-`re` divergence (\b, $, backreference
// case folding, greedy backtracking) that the curated fixtures cannot cover.

enum FuzzGoldens {
    static let cases: [(raw: String, expected: String)] = [
        ("full\nwait\terr tomorrow to com\nnew\ttomorrow  for", "full\nwait\terr tomorrow to com\nnew\ttomorrow for"),
        ("on\nscratch :\nuhh\nperiod\nbar err ,\nuhm with uh", "on\nscratch:\n\nperiod\nbar err,\nwith"),
        ("um\tkhatri", "khatri"),
        ("xyz \t\nuhm\tcom", "xyz\ncom"),
        ("bar\nbob um erm\tthe  uh uh com", "bar\nbob the com"),
        ("john paragraph ! tomorrow\tsharique for", "john paragraph! tomorrow\tsharique for"),
        ("museum\npoint point  example foo", "museum\npoint point example foo"),
        ("wait  bar , ;", "wait bar,;"),
        ("um  !  tomorrow dot with\ntoday\term  example of\tto", "! tomorrow dot with\ntoday example of\tto"),
        ("an acme\noutlook\tfull\texclamation\tkhatri\tto\tfor  and world\nbob", "an acme\noutlook\tfull\texclamation\tkhatri\tto\tfor and world\nbob"),
        ("to\twait  ?\toutlook\nkhatri\na bar don't\tmuseum\toutlook\term", "to\twait?\toutlook\nkhatri\na bar don't\tmuseum\toutlook"),
        ("org\t: \n", "org:"),
        ("?  hello\nstop\nor was  , . point  com  wait today\nmuseum", "? hello\nstop\nor was,. point com wait today\nmuseum"),
        ("acme khatri example 123", "acme khatri example 123"),
        ("a  i hello\nxyz", "a i hello\nxyz"),
        ("\t uhh\tin  : it\ntoday : uhm : a", "in: it\ntoday:: a"),
        ("of\nexample i bob sharique  today today uh", "of\nexample i bob sharique today today"),
        ("tomorrow i    and\tdev   \tor it new", "tomorrow i and\tdev or it new"),
        ("com\nworld\tfor\torg\nscratch err  123\tcom period", "com\nworld\tfor\torg\nscratch err 123\tcom."),
        ("at\tnew\nwith  i", "at\tnew\nwith i"),
        ("com  io of\nuhm foo\nhello no", "com io of\nfoo\nhello no"),
        ("a\npoint acme\ndev tomorrow that\nan question \t gmail\n:\tbar", "a\npoint acme\ndev tomorrow that\nan question gmail:\tbar"),
        ("com\tworld alice it khatri alice\n  \na", "com\tworld alice it khatri alice\n\na"),
        ("dev", "dev"),
        ("with", "with"),
        ("with erm io don't  today err\npoint  mark  the\t!  paragraph", "with io don't today err\npoint mark the! paragraph"),
        ("the foo   ", "the foo"),
        ("don't\tuh  ;  uhm  !  bob example scratch", "don't;! bob example scratch"),
        ("today\terr .\nuhm museum\noutlook\twas me ;", "today\terr.\nmuseum\noutlook\twas me;"),
        ("erm", ""),
        ("err  is at  was\numm\tstop", "err is at was\nstop"),
        ("wait", "wait"),
        ("a for .\nin\ntoday . question at", "a for.\nin\ntoday. question at"),
        ("point mark umm\tme wait to world\twith io\nan  \n\n123", "point mark me wait to world\twith io\nan\n\n123"),
        (", new\nthat\thello\nscratch of uhm\nquestion\n. the", ", new\nthat\thello\nscratch of\nquestion. the"),
        ("mark  outlook bob\nuh\terr gmail\tand bob", "mark outlook bob\nerr gmail\tand bob"),
        ("scratch", "scratch"),
        ("wait . no wait", "wait. no wait"),
        ("um mark\nscratch io alice  : ,", "mark\nscratch io alice:,"),
        ("\t new\tio\ndev   \tto  period no in\ni\tfull  no", "new\tio\ndev to period no in\ni\tfull no"),
        ("   acme period\numm period\nkhatri  um stop\tkhatri", "acme period\nperiod\nkhatri stop\tkhatri"),
        (":\terr err\ton i\thello foo  example khatri", ":\terr err\ton i\thello foo example khatri"),
        ("wait scratch", "wait scratch"),
        ("full museum\nline", "full museum\nline"),
        ("wait\nno\toutlook and    museum\tbob\njohn  umm ?", "wait\nno\toutlook and museum\tbob\njohn?"),
        ("org that  ? museum\tjohn\tdev example full  gmail point\t   today", "org that? museum\tjohn\tdev example full gmail point today"),
        ("gmail  um\nit tomorrow at org mark dev  io \t  uhm point", "gmail\nit tomorrow at org mark dev io point"),
        ("    is", "is"),
        ("line\tscratch\n! wait err alice", "line\tscratch! wait err alice"),
        ("museum\tumm\ti\tthat  the\t.  no  sharique\t! uhh", "museum i\tthat the. no sharique!"),
        ("example alice me ,  acme\ta : of for\tsharique io", "example alice me, acme\ta: of for\tsharique io"),
        ("gmail", "gmail"),
        ("gmail outlook", "gmail outlook"),
        ("me\nperiod on", "me\nperiod on"),
        ("world\tfoo acme and", "world\tfoo acme and"),
        ("was i  acme", "was i acme"),
        ("acme", "acme"),
        ("bob today\tin khatri  tomorrow to an example", "bob today\tin khatri tomorrow to an example"),
        ("a\nit um com is ?  uh", "a\nit com is?"),
        ("period it on question  no khatri ,\toutlook today on", "period it on question no khatri,\toutlook today on"),
        ("of \n  in on an", "of\nin on an"),
        ("i\tbar umm  123\tum\tio\ntoday\ttomorrow\tdev\tno", "i\tbar 123 io\ntoday\ttomorrow\tdev\tno"),
        (": sharique on\nnew\tfull .\ni  john to for", ": sharique on\nnew\tfull.\ni john to for"),
        ("an the\toutlook museum  no", "an the\toutlook museum no"),
        ("; full in the", "; full in the"),
        ("khatri to  ,", "khatri to,"),
        ("gmail\txyz  \n uhh uhm", "gmail\txyz"),
        (".", "."),
        ("bob\nfoo um\nscratch\n\n world museum", "bob\nfoo\nscratch\n\nworld museum"),
        ("that\nwas ! scratch period the um", "that\nwas! scratch period the"),
        ("a full  tomorrow don't uh", "a full tomorrow don't"),
        ("erm sharique\nexclamation\nworld\t, an uhh\tcom\n\n\tuhh", "sharique\nexclamation\nworld, an com"),
        ("uhh  \t  question\tumm", "question"),
        ("um  don't bob", "don't bob"),
        ("acme wait exclamation tomorrow\non umm  um\nuh", "acme wait exclamation tomorrow\non"),
        ("today example  bar", "today example bar"),
        ("  ", ""),
        ("  \ncom a\tparagraph org", "com a\tparagraph org"),
        ("org\txyz", "org\txyz"),
        ("on com outlook\t,  today\nstop paragraph\texclamation bar me .", "on com outlook, today\nstop paragraph\texclamation bar me."),
        ("tomorrow paragraph ! is\ttoday", "tomorrow paragraph! is\ttoday"),
        ("to gmail\n:  was xyz\ni", "to gmail: was xyz\ni"),
        (".\tpoint\nquestion  , wait\na\nto\nparagraph\ntoday io paragraph foo", ".\tpoint\nquestion, wait\na\nto\nparagraph\ntoday io paragraph foo"),
        ("was\tfor\nhello line on period full to\nline line  \t", "was\tfor\nhello line on period full to\nline line"),
        ("dot acme is an\tfor\tworld   \ndon't no line wait", "dot acme is an\tfor\tworld\ndon't no line wait"),
        (",\tfoo acme umm\nwas of \t\term", ",\tfoo acme\nwas of"),
        ("of uhh stop umm mark\tworld", "of stop mark\tworld"),
        ("; uhh", ";"),
        ("um", ""),
        ("org\tbar io  tomorrow it\ndot example i : question\ntomorrow\tworld", "org\tbar io tomorrow it\ndot example i: question\ntomorrow\tworld"),
        ("acme\texclamation\txyz john", "acme\texclamation\txyz john"),
        ("xyz  bar\terr for example  umm\tbar", "xyz bar\terr for example bar"),
        ("\t with\tpoint\na uhm ,\nacme dot paragraph", "with\tpoint\na,\nacme dot paragraph"),
        ("outlook\t\n\t;", "outlook;"),
        ("stop  for", "stop for"),
        ("; was\nperiod point point\nstop\n   outlook ! question\nquestion\na", "; was\nperiod point point\nstop\noutlook! question\nquestion\na"),
        ("acme\nor it umm\talice org", "acme\nor it alice org"),
        ("xyz\t; erm\nquestion", "xyz;\nquestion"),
        ("umm bar\tperiod\non\t;", "bar\tperiod\non;"),
        ("dot  the ;", "dot the;"),
        ("khatri\nstop is\txyz\t   mark  um question me", "khatri\nstop is\txyz mark question me"),
        ("full ;\tuhh\nuhh\nline\nbob outlook  io\norg  line \n", "full;\n\nline\nbob outlook io\norg line"),
        (":\tme  of !\n.  today with today", ":\tme of!. today with today"),
        ("com", "com"),
        ("line period\tuhh\nat foo\tfull\tumm  exclamation  museum\tbob", "line period\nat foo\tfull exclamation museum\tbob"),
        ("an", "an"),
        ("a museum\tumm uhm\na bob", "a museum\na bob"),
        (":  no\nor um err at", ": no\nor err at"),
        ("is  and full new i museum  com it to . bar", "is and full new i museum com it to. bar"),
        ("? \n full  and  to\tum acme in", "?\nfull and to acme in"),
        ("question ;\nnew  world  uhh  me\nuhh  sharique  point um", "question;\nnew world me\nsharique point"),
        ("err  line mark on\tgmail  wait was", "err line mark on\tgmail wait was"),
        ("or\nmark new\tum paragraph com hello", "or\nmark\n\ncom hello"),
        ("stop\nand  uhh outlook point\nalice", "stop\nand outlook point\nalice"),
        ("org an  \n ; 123 err\nerm hello", "org an; 123 err\nhello"),
        ("uhm org  umm scratch\tstop example  123", "org scratch\tstop example 123"),
        ("sharique\terr point uhm today  paragraph ,  sharique with\nscratch  today\t!", "sharique\terr point today paragraph, sharique with\nscratch today!"),
        ("bar", "bar"),
        ("io\nuhm\nfor\texclamation\nto .  bar  with\nmark\tbob\nio\nmark", "io\n\nfor\texclamation\nto. bar with\nmark\tbob\nio\nmark"),
        ("a\tuhh\tor\t?  tomorrow\ntoday me\n.\tor", "a or? tomorrow\ntoday me.\tor"),
        ("um a\talice\nwait bob\talice\nscratch io\nstop  dot i umm", "a\talice\nwait bob\talice\nscratch io\nstop dot i"),
        ("\t \t", ""),
        ("john\tscratch  123 stop museum um was ,  acme  xyz", "john\tscratch 123 stop museum was, acme xyz"),
        ("and mark stop sharique", "and mark stop sharique"),
        (". example  alice", ". example alice"),
        ("uh umm\t\t \t\ta sharique sharique world", "a sharique sharique world"),
        ("mark\nand\nworld\nfoo\texclamation foo outlook outlook com a", "mark\nand\nworld\nfoo\texclamation foo outlook outlook com a"),
        ("of\nmuseum\tmark example today", "of\nmuseum\tmark example today"),
        ("was\twait question for line \t period\nalice\ttomorrow  the\tgmail", "was\twait question for line period\nalice\ttomorrow the\tgmail"),
        ("world     bar\nkhatri\ttoday  uhm of question question\tto", "world bar\nkhatri\ttoday of question question\tto"),
        ("it to \n", "it to"),
        ("wait io mark", "wait io mark"),
        (",  ?\tperiod and", ",?\tperiod and"),
        ("khatri  alice for\nfoo com  today\n: com an scratch paragraph line", "khatri alice for\nfoo com today: com an scratch paragraph line"),
        ("of  mark io museum\nfor uhm  , mark\t123", "of mark io museum\nfor, mark\t123"),
        ("on  io\njohn uhm\tfull\tsharique dev is\nmark sharique\nor", "on io\njohn full\tsharique dev is\nmark sharique\nor"),
        ("erm\n,\noutlook khatri acme\tmuseum  is\t! no", ",\noutlook khatri acme\tmuseum is! no"),
        (";  acme\tdot  exclamation", "; acme\tdot exclamation"),
        ("is  io", "is io"),
        ("at uh", "at"),
        ("today ! io  uh  and\nof paragraph\n  \njohn uhm     with", "today! io and\nof paragraph\n\njohn with"),
        ("khatri\t? john  gmail example uh museum", "khatri? john gmail example museum"),
        ("of\t! outlook", "of! outlook"),
        ("bob dot erm\tgmail  alice an", "bob dot gmail alice an"),
        ("   \t  paragraph  point gmail full at", "paragraph point gmail full at"),
        ("   that stop dev\nbar world  uhm is", "that stop dev\nbar world is"),
        ("no\non with 123  museum wait", "no\non with 123 museum wait"),
        ("to\nsharique bar with\nnew the in  point mark\twas", "to\nsharique bar with\nnew the in point mark\twas"),
        ("org\nexclamation\ni  that", "org\nexclamation\ni that"),
        ("khatri\noutlook .\nworld line", "khatri\noutlook.\nworld line"),
        ("period\nscratch  john paragraph the  is", "period\nscratch john paragraph the is"),
        ("erm  or ;\tbar\tuhh \n  stop\tdev \n bar\nacme", "or;\tbar\nstop\tdev\nbar\nacme"),
        ("i\tbar", "i\tbar"),
        ("example is\nfoo\nat  full with\n\n uhh a point", "example is\nfoo\nat full with\n\na point"),
        ("khatri\n; was scratch with", "khatri; was scratch with"),
        ("world ?   \nquestion  123\norg sharique wait no to an", "world?\nquestion 123\norg sharique wait no to an"),
        ("hello sharique stop\tin ! i \n\tfoo at", "hello sharique stop\tin! i\nfoo at"),
        ("alice\tparagraph  it\tfull com i , sharique\twait scratch", "alice\tparagraph it\tfull com i, sharique\twait scratch"),
        (",  sharique john\tme\nworld \n", ", sharique john\tme\nworld"),
        ("with on khatri the  mark foo\tuhh  org  \n", "with on khatri the mark foo org"),
        ("err", "err"),
        ("it a  period org new at uh dev foo", "it a period org new at dev foo"),
        ("\t\ntomorrow me the at  scratch", "tomorrow me the at scratch"),
        ("\t\tkhatri  uhh", "khatri"),
        ("john\tuh a\tthe at    exclamation sharique bob  bar", "john a\tthe at exclamation sharique bob bar"),
        (",  at on\t! that\ndon't uhm\tis dot", ", at on! that\ndon't is dot"),
        ("uh\nat outlook ,  was scratch bob", "at outlook, was scratch bob"),
        (", err com\tcom a tomorrow\nio\n;\tit\ndon't\tquestion", ", err com\tcom a tomorrow\nio;\tit\ndon't\tquestion"),
        ("hello and ? for  new bar", "hello and? for new bar"),
        ("on scratch io io\nexclamation question bar  to\tfull", "on scratch io io\nexclamation question bar to\tfull"),
        ("that", "that"),
        ("period  at\n,\nthat\nto\ntomorrow", "period at,\nthat\nto\ntomorrow"),
        ("example\n,\ni question", "example,\ni question"),
        ("me\t! new\nor\n\t\tline example\n:\tfor  \t", "me! new\nor\nline example:\tfor"),
        (";\tuhm   \njohn an  on\tnew\tscratch\tof", ";\njohn an on\tnew\tscratch\tof"),
        ("john hello\tthe\ta\tfull with dev\nin khatri tomorrow", "john hello\tthe\ta\tfull with dev\nin khatri tomorrow"),
        ("bar  example\t. paragraph  for full", "bar example. paragraph for full"),
        ("of john\tor\tmark\tline\nmuseum\tand don't erm\nin  \n tomorrow", "of john\tor\tmark\tline\nmuseum\tand don't\nin\ntomorrow"),
        ("acme\nhello\ttoday john\tumm\non  um", "acme\nhello\ttoday john\non"),
        ("me\ttoday or with at dot  point  example", "me\ttoday or with at dot point example"),
        ("bob bob  on  question  was don't :", "bob bob on question was don't:"),
        ("question\n;  uh . wait\tit", "question;. wait\tit"),
        ("line \t", "line"),
        (",", ","),
        ("me\tin\tno\n? \t\nwait\tof\torg an uh", "me\tin\tno?\nwait\tof\torg an"),
        ("period 123 stop  me   \tparagraph  uh \t example", "period 123 stop me paragraph example"),
        ("org  for\nxyz\nscratch\nexclamation a\nparagraph uh  is foo hello or", "org for\nxyz\nscratch\nexclamation a\nparagraph is foo hello or"),
        ("wait\t\t  io acme     uhm point", "wait io acme point"),
        ("gmail  line  hello was", "gmail line hello was"),
        ("org\nto\n; ; xyz bob is of", "org\nto;; xyz bob is of"),
        ("on in", "on in"),
        ("dev\nkhatri was world", "dev\nkhatri was world"),
        ("err for\tit  bob  or wait\ttoday\nline", "err for\tit bob or wait\ttoday\nline"),
        ("io  an", "io an"),
        ("umm  point  and  line museum\nworld", "point and line museum\nworld"),
        ("it  123 or\ton : new\terr  um", "it 123 or\ton: new\terr"),
        ("for\ni  example sharique\tand\t.", "for\ni example sharique\tand."),
        ("to\nwas to", "to\nwas to"),
        ("was mark\nan\tuhh  at bob\n123\tan\tthe museum me", "was mark\nan at bob\n123\tan\tthe museum me"),
        ("org don't in wait\n? sharique  for    on io  gmail museum", "org don't in wait? sharique for on io gmail museum"),
        ("of full  stop umm sharique\nnew  hello  on i \n uhh  bar", "of full stop sharique\nnew hello on i\nbar"),
        ("outlook  of mark me  uhh", "outlook of mark me"),
        ("example is  gmail ; today org ?", "example is gmail; today org?"),
        ("um\toutlook io full at with alice org", "outlook io full at with alice org"),
        ("umm khatri  gmail\nin  point  outlook     alice umm", "khatri gmail\nin point outlook alice"),
        ("khatri khatri  org\tjohn\num umm khatri\n123 hello ? full   ", "khatri khatri org\tjohn\nkhatri\n123 hello? full"),
        ("that\non\tme gmail\nin that uh\nscratch stop org\twith", "that\non\tme gmail\nin that\nscratch stop org\twith"),
        ("i um  a a\n\t on a  uhh", "i a\non a"),
        ("on  , that", "on, that"),
        ("gmail at\ndon't was", "gmail at\ndon't was"),
        ("paragraph at\n123 wait that with  khatri", "paragraph at\n123 wait that with khatri"),
        ("umm\tfull\n\n\tacme\nmark  mark today", "full\n\nacme\nmark mark today"),
        ("example example", "example example"),
        ("stop today in on\tquestion\tnew", "stop today in on\tquestion\tnew"),
        ("or    \tof  khatri\non example period\nfor  com", "or of khatri\non example period\nfor com"),
        ("john", "john"),
        ("it\ntoday um gmail is\n!", "it\ntoday gmail is!"),
        ("world  dev\ndon't , um and it  is  paragraph outlook erm", "world dev\ndon't, and it is paragraph outlook"),
        ("no on was  com  stop outlook\nbob 123  museum ;", "no on was com stop outlook\nbob 123 museum;"),
        ("outlook stop\nfull  org stop outlook\n123 me\nuhh", "outlook stop\nfull org stop outlook\n123 me"),
        ("in\nin  khatri\ngmail 123 museum", "in khatri\ngmail 123 museum"),
        ("example to  sharique\n? bob museum\n,", "example to sharique? bob museum,"),
        ("bob  !   ", "bob!"),
        ("err uhh period a xyz\ni line\nline", "err period a xyz\ni line\nline"),
        ("me hello\texample alice stop tomorrow tomorrow hello\thello", "me hello\texample alice stop tomorrow tomorrow hello\thello"),
        ("umm\n123\t\t", "123"),
        ("exclamation\toutlook alice and", "exclamation\toutlook alice and"),
        ("erm alice\tto example\txyz", "alice\tto example\txyz"),
        ("today gmail\nnew\t  \nfoo", "today gmail\nnew\nfoo"),
        ("outlook bar", "outlook bar"),
        ("dot\nscratch  i hello\tline  that\n\n\tno  full ,\nbob", "dot\nscratch i hello\tline that\n\nno full,\nbob"),
        ("khatri today org  outlook and dev  com", "khatri today org outlook and dev com"),
        ("foo  world\tbar\tthat", "foo world\tbar\tthat"),
        ("stop to and  full don't", "stop to and full don't"),
        ("io me\nstop bob uhm  khatri", "io me\nstop bob khatri"),
        ("alice xyz umm\nexclamation  period and", "alice xyz\nexclamation period and"),
        (":", ":"),
        ("io\njohn don't an", "io\njohn don't an"),
        ("example . dot :", "example. dot:"),
        ("full wait the\nor", "full wait the\nor"),
        ("world umm\tbar\ni\tthe i", "world bar\ni\tthe i"),
        ("mark\thello\tat question  of ! of an  \t\tmark", "mark\thello\tat question of! of an mark"),
        ("that exclamation  io\non line me\ton\nat  err", "that exclamation io\non line me\ton\nat err"),
        ("sharique at", "sharique at"),
        ("wait\n\n an um an an for  on", "wait\n\nan for on"),
        ("acme\na ; bob ?  com\nbob acme exclamation", "acme\na; bob? com\nbob acme exclamation"),
        ("uhh  and dev\tin\nalice\tgmail museum org example full com scratch", "and dev\tin\nalice\tgmail museum org example full com scratch"),
        ("tomorrow\tfoo example bar", "tomorrow\tfoo example bar"),
        ("me new com", "me new com"),
        ("at bob umm i a the", "at bob i a the"),
        ("xyz erm\nat", "xyz\nat"),
        ("alice , or question\nuh\ttoday", "alice, or question\ntoday"),
        ("erm\nand\ndot", "and\ndot"),
        ("to  and exclamation example", "to and exclamation example"),
        ("bob \t at of  xyz  err uh 123\tto", "bob at of xyz err 123\tto"),
        ("john\tme\ngmail\txyz  dev \n\npoint\num\ndon't", "john\tme\ngmail\txyz dev\n\npoint\n\ndon't"),
        ("john org\nor  \t  or", "john org\nor"),
        ("uh\nsharique io that\nto", "sharique io that\nto"),
        ("world world scratch\tum paragraph bar that", "world world scratch paragraph bar that"),
        ("at org   \tthe  xyz\tfull", "at org the xyz\tfull"),
        (".\tno\nexample err or no uh", ".\tno\nexample err or no"),
        ("on of 123\nperiod dot it acme  io\n   with paragraph in", "on of 123\nperiod dot it acme io\nwith paragraph in"),
        ("dot\nthat exclamation", "dot\nthat exclamation"),
        ("point\tthe  alice", "point\tthe alice"),
        ("new\tmuseum  alice\ndot  tomorrow\ttoday\na and\tpoint line\nquestion", "new\tmuseum alice\ndot tomorrow\ttoday\na and\tpoint line\nquestion"),
        ("it", "it"),
        ("or  world\tsharique  \n\nwas at mark\tno\tuh\nmuseum", "or world\tsharique\n\nwas at mark\tno\nmuseum"),
        (": on\nto \t ?\tof\t? question is was", ": on\nto?\tof? question is was"),
        ("period\nuhh\tpoint today\torg", "period\npoint today\torg"),
        ("an\tof sharique\tio  bar", "an\tof sharique\tio bar"),
        ("new point\n123\n123  stop\tscratch on  i\non ;  to", "new point\n123\n123 stop\tscratch on i\non; to"),
        ("me !\ttomorrow\ttomorrow scratch alice world outlook", "me!\ttomorrow\ttomorrow scratch alice world outlook"),
        ("wait\tmark", "wait\tmark"),
        ("or hello  of\tsharique !\npoint is  line umm", "or hello of\tsharique!\npoint is line"),
        ("a\t! io me", "a! io me"),
        ("?  it  full\nscratch\nwith", "? it full\nscratch\nwith"),
        ("org gmail world\nscratch : paragraph", "org gmail world\nscratch: paragraph"),
        ("that period question on", "that period question on"),
        ("  \nwith no  erm\t.", "with no."),
        ("question museum stop  was  hello  gmail an 123 dot", "question museum stop was hello gmail an 123 dot"),
        ("hello . line  \n ,\nthat scratch", "hello. line,\nthat scratch"),
        ("new", "new"),
        ("don't was\tfor\tacme to  tomorrow xyz  err", "don't was\tfor\tacme to tomorrow xyz err"),
        ("museum  bob  and  period  was uh new\nexclamation outlook", "museum bob and period was new\nexclamation outlook"),
        ("umm", ""),
        ("uh !\txyz", "!\txyz"),
        ("umm\nin \n\nwith alice\tbob umm  world  and sharique\t;", "in\n\nwith alice\tbob world and sharique;"),
        ("!\nperiod\t: new\tworld\tfoo  no", "!\nperiod: new\tworld\tfoo no"),
        ("tomorrow \n\nuh      at", "tomorrow\n\nat"),
        ("today mark hello example period dot ,\tfull\nscratch\tbob\tworld", "today mark hello example period dot,\tfull\nscratch\tbob\tworld"),
        ("erm\n;  xyz sharique\tfoo hello", "; xyz sharique\tfoo hello"),
        ("and khatri umm erm  err dot  i at\talice  erm", "and khatri err dot i at\talice"),
        ("?\tumm org john uhh\nit ?", "? org john\nit?"),
        ("point exclamation i", "point exclamation i"),
        ("in ; at com ? question\n?\nxyz uhh  world in", "in; at com? question?\nxyz world in"),
        ("dot \t  alice !", "dot alice!"),
        ("dot\ti\nor  \t\t;  umm museum", "dot\ti\nor; museum"),
        ("\t\toutlook that uhm", "outlook that"),
        ("new\n\n", "new"),
        ("museum it an tomorrow\tpoint\talice bar wait !\t. gmail it", "museum it an tomorrow\tpoint\talice bar wait!. gmail it"),
        ("new\tfoo\norg bob no", "new\tfoo\norg bob no"),
        ("foo", "foo"),
        ("scratch\tthat sharique  io line\nno\nthat", "sharique io line\nno\nthat"),
        ("period exclamation  ? xyz  paragraph  with", "period exclamation? xyz paragraph with"),
        ("; dot\tstop\nthe stop xyz", "; dot\tstop\nthe stop xyz"),
        ("dev \n bob erm\twith  don't", "dev\nbob with don't"),
        ("new\nof io of  for me\tthat", "new\nof io of for me\tthat"),
        ("to\tfor it\nmuseum", "to\tfor it\nmuseum"),
        ("stop on", "stop on"),
        ("foo\tjohn\tor\nan\ttomorrow\n\t an\nerm  tomorrow exclamation\nexclamation\ttoday", "foo\tjohn\tor\nan\ttomorrow\nan\ntomorrow exclamation\nexclamation\ttoday"),
        ("bob on example period i\nof dot", "bob on example period i\nof dot"),
        ("a exclamation\njohn  io\nerm\nis example dev\n;", "a exclamation\njohn io\n\nis example dev;"),
        ("acme  question\nwas full  museum \n\tcom point\nmark\nquestion\tnew \n", "acme question\nwas full museum\ncom point\nmark\nquestion\tnew"),
        ("on xyz outlook\tto  \n \t\talice at dev", "on xyz outlook\tto\nalice at dev"),
        ("tomorrow  uhh\nerm ,  erm\non uh", "tomorrow,\non"),
        ("to", "to"),
        ("org that  . err\nwait mark", "org that. err\nwait mark"),
        ("don't , gmail  gmail\tdot", "don't, gmail gmail\tdot"),
        ("foo \n don't  alice \n on  of ? . acme\terr\noutlook", "foo\ndon't alice\non of?. acme\terr\noutlook"),
        ("! i\tno  hello", "! i\tno hello"),
        (", tomorrow 123     umm foo an\nsharique exclamation", ", tomorrow 123 foo an\nsharique exclamation"),
        ("exclamation  to  question for to i\nmuseum sharique  .", "exclamation to question for to i\nmuseum sharique."),
        ("paragraph\nparagraph museum\tmuseum\tat", "paragraph\nparagraph museum\tmuseum\tat"),
        ("for", "for"),
        ("point\nerm\nworld\tscratch uh\nbar with io wait stop \t erm", "point\n\nworld\tscratch\nbar with io wait stop"),
        ("example dev\nto a\nbob\t\t a , bob exclamation  xyz", "example dev\nto a\nbob a, bob exclamation xyz"),
        ("gmail  wait uhh  err an point", "gmail wait err an point"),
        ("that\talice", "that\talice"),
        ("sharique", "sharique"),
        ("of and new\tmuseum uhh\ta", "of and new\tmuseum a"),
        ("of  erm\n.  umm\nto don't err an is\n:", "of.\nto don't err an is:"),
        ("hello\tuh\term  dot  sharique with erm \t\nacme", "hello dot sharique with\nacme"),
        ("umm  period\texample foo", "period\texample foo"),
        ("hello  !\nuhm\tkhatri stop in\nit khatri or\n!", "hello!\nkhatri stop in\nit khatri or!"),
        ("was 123 the\tuh\nand  it sharique", "was 123 the\nand it sharique"),
        ("exclamation com\tmuseum\n:  acme", "exclamation com\tmuseum: acme"),
        ("an\nuh  uhh 123", "an\n123"),
        ("today", "today"),
        ("err xyz   \t    on\nof bar  dot : point org bar", "err xyz on\nof bar dot: point org bar"),
        ("\t full\tbob  exclamation\tmark\nparagraph museum\nacme museum\nfoo", "full\tbob exclamation\tmark\nparagraph museum\nacme museum\nfoo"),
        ("that\nerr com umm xyz\norg to  com    dev umm", "that\nerr com xyz\norg to com dev"),
        ("with don't period\noutlook erm", "with don't period\noutlook"),
        ("org com  museum\nwas  hello", "org com museum\nwas hello"),
        ("on paragraph", "on paragraph"),
        ("world wait  gmail  world it\num    \nuhm  full\nof  an", "world wait gmail world it\n\nfull\nof an"),
        ("scratch  : a question : world\twith\n\t com\nme period  me", "scratch: a question: world\twith\ncom\nme period me"),
        (". an io", ". an io"),
        ("wait io\tis  .\nme no\nwith  it  new\nscratch  line\nfoo", "wait io\tis.\nme no\nwith it new\nscratch line\nfoo"),
        ("bar org\term full tomorrow\nexample john  new today", "bar org full tomorrow\nexample john new today"),
        ("me : was  mark", "me: was mark"),
        ("alice question\nthat  foo\non\n.  is err example  bar", "alice question\nthat foo\non. is err example bar"),
        ("i\tbob line tomorrow sharique 123\nto", "i\tbob line tomorrow sharique 123\nto"),
        ("full\nto it\t! khatri", "full\nto it! khatri"),
        ("com\tbar\n.    uhh\ntomorrow\t; full\tno  world question\tjohn", "com\tbar.\ntomorrow; full\tno world question\tjohn"),
        ("point john uhh \t\nkhatri\nmuseum stop", "point john\nkhatri\nmuseum stop"),
        ("foo umm\tan", "foo an"),
        ("at  wait on\nbob hello for for\tuhh  123\t\t", "at wait on\nbob hello for 123"),
        (". err", ". err"),
        ("that uh outlook  with  scratch\n   stop", "that outlook with scratch\nstop"),
        ("gmail  it  khatri  \t and full\n\t world world", "gmail it khatri and full\nworld world"),
        ("for\n!  of\nerm acme  exclamation example mark  \n umm\n,", "for! of\nacme exclamation example mark,"),
        ("! full err world\tno at\nsharique\nwait ?\tumm", "! full err world\tno at\nsharique\nwait?"),
        ("period  today  at\tan wait", "period today at\tan wait"),
        ("don't xyz on dev world new dev     org", "don't xyz on dev world new dev org"),
        ("the", "the"),
        ("question erm  alice  . uh com", "question alice. com"),
        ("new foo mark", "new foo mark"),
        ("line com\texample\nmuseum\nstop today outlook outlook  with with", "line com\texample\nmuseum\nstop today outlook outlook with"),
        ("exclamation\ta  is a", "exclamation\ta is a"),
        ("for foo  at .\n.\tor  line  xyz example\nfull     gmail", "for foo at..\tor line xyz example\nfull gmail"),
        ("org\tgmail sharique ! umm example\t;\tum  com", "org\tgmail sharique! example; com"),
        ("\n", ""),
        ("period an", "period an"),
        ("  \tuhm err\non\nbob umm\ndot for\ttoday  bar", "err\non\nbob\ndot for\ttoday bar"),
        ("john 123  123  org\twas\ton  of that", "john 123 123 org\twas\ton of that"),
        ("outlook\nto i dev", "outlook\nto i dev"),
        ("\t", ""),
        ("dot\nwith   \ttomorrow  and of\nand\tdon't sharique uhh exclamation", "dot\nwith tomorrow and of\nand\tdon't sharique exclamation"),
        ("it  on org", "it on org"),
        ("dot hello", "dot hello"),
        ("mark  line", "mark line"),
        ("at\tmark  full umm was\twait \n  org", "at\tmark full was\twait\norg"),
        ("and io museum  . com hello and 123\nthe uhh  is is", "and io museum. com hello and 123\nthe is"),
        ("khatri uh\t!\nit\n! that\nuhm", "khatri!\nit! that"),
        ("new org\tin  io gmail  org museum\n. a i\tuhh ,", "new org\tin io gmail org museum. a i,"),
        ("of xyz acme\tfoo\tmuseum on\nperiod\nbob", "of xyz acme\tfoo\tmuseum on\nperiod\nbob"),
        ("123 xyz\nworld\nan sharique\n!  of sharique of at ; bar", "123 xyz\nworld\nan sharique! of sharique of at; bar"),
        ("line\nto  bob and\t;", "line\nto bob and;"),
        ("i   \n123\nbob a\nnew  hello a gmail", "i\n123\nbob a\nnew hello a gmail"),
        ("mark\toutlook \n ? museum the , io  err com\t.  dev", "mark\toutlook? museum the, io err com. dev"),
        (".\nnew\tbar", ".\nnew\tbar"),
        ("foo\nat no today : stop", "foo\nat no today: stop"),
        ("um exclamation", "exclamation"),
        ("xyz  is dev\nexclamation", "xyz is dev\nexclamation"),
        ("\n\n; of err  uh uhm\nstop  i\tstop", "; of err\nstop i\tstop"),
        ("sharique that", "sharique that"),
        ("erm or\nworld", "or\nworld"),
        ("123 stop\twith ,", "123 stop\twith,"),
        ("no", "no"),
        ("paragraph foo  mark", "paragraph foo mark"),
    ]
}
