// GENERATED — do not hand-edit. Regenerate with:
//   ~/.meetingscribe/venv/bin/python pp_gen_goldens.py > Tests/WispritPostProcessTests/Goldens.swift
// Every expectation below is the literal return value of the Python
// wisprit.postprocess.process() run on this machine.

enum Goldens {
    static let defaults: [(raw: String, expected: String)] = [
        ("um hello world", "hello world"),
        ("so um I think uh we should go", "so I think we should go"),
        ("uh, let's start", "let's start"),
        ("well um yeah", "well yeah"),
        ("erm okay", "okay"),
        ("this is umm a test", "this is a test"),
        ("the museum was empty", "the museum was empty"),
        ("humble beginnings", "humble beginnings"),
        ("ermine fur", "ermine fur"),
        ("a rumble in the distance", "a rumble in the distance"),
        ("I like summer", "I like summer"),
        ("so we can do this", "so we can do this"),
        ("you know the answer already", "you know the answer already"),
        ("well, that is interesting", "well, that is interesting"),
        ("the period at the end of an era", "the period at the end of an era"),
        ("she scratched the surface", "she scratched the surface"),
        ("a new line of business opened downtown", "a new line of business opened downtown"),
        ("meet at the dot matrix printer", "meet at the dot matrix printer"),
        ("he said hello", "he said hello"),
        ("let's talk about the comma splice problem", "let's talk about the comma splice problem"),
        ("err on the side of caution", "err on the side of caution"),
        ("to err is human", "to err is human"),
        ("sharique dot khatri at gmail dot com", "sharique.khatri@gmail.com"),
        ("reach me at a dot b dot c at foo dot io", "reach me at a.b.c@foo.io"),
        ("john at gmail dot com", "john@gmail.com"),
        ("ping me at someone at outlook dot com", "ping me at someone@outlook.com"),
        ("email me at john at example dot com", "email me at john at example.com"),
        ("contact support at company dot org", "contact support at company.org"),
        ("go to example dot com", "go to example.com"),
        ("visit my site at portfolio dot dev", "visit my site at portfolio.dev"),
        ("the repo is github dot com", "the repo is github.com"),
        ("sub dot example dot org", "sub.example.org"),
        ("connect the dot puzzle", "connect the dot puzzle"),
        ("first line new line second line", "first line\nsecond line"),
        ("intro new paragraph body", "intro\n\nbody"),
        ("are you coming question mark", "are you coming?"),
        ("watch out exclamation point", "watch out!"),
        ("that is the end period", "that is the end."),
        ("stop right there exclamation mark", "stop right there!"),
        ("meet at three no wait four pm", "meet at four pm"),
        ("send it to Bob no wait Alice", "send it to Alice"),
        ("the total is ten no wait twelve dollars", "the total is twelve dollars"),
        ("call him tomorrow scratch that today", "today"),
        ("draft the email scratch that write the memo", "write the memo"),
        ("please wait for me", "please wait for me"),
        ("I can hardly wait", "I can hardly wait"),
        ("no I disagree", "no I disagree"),
        ("hello   world", "hello world"),
        ("hello , world", "hello, world"),
        ("wait   .  stop", "wait. stop"),
        ("line one \n line two", "line one\nline two"),
        ("  leading and trailing  ", "leading and trailing"),
        ("um", ""),
        ("um um um", ""),
        ("UM Hello UH world", "Hello world"),
        ("Umm, okay then", "okay then"),
        ("uhm... right", "... right"),
        ("erm, erm, erm", ""),
        ("album umbrella umpire", "album umbrella umpire"),
        ("uh-huh", "-huh"),
        ("he said um, and then uh, nothing", "he said and then nothing"),
        ("first dot last at proton dot me", "first.last@proton.me"),
        ("a dot b at c dot d dot com", "a.b@c.d.com"),
        ("info at fastmail dot com", "info@fastmail.com"),
        ("Sharique dot Khatri at GMAIL dot COM", "Sharique.Khatri@GMAIL.COM"),
        ("reach out at hello at zoho dot com please", "reach out at hello@zoho.com please"),
        ("the docs live at docs dot python dot org", "the docs live at docs.python.org"),
        ("check news dot ycombinator dot com now", "check news.ycombinator.com now"),
        ("team at acme dot co", "team at acme.co"),
        ("my handle at msn dot com", "my handle@msn.com"),
        ("server dot local dot lan", "server dot local dot lan"),
        ("he is at home", "he is at home"),
        ("x dot y at unknownhost dot xyz", "x dot y at unknownhost dot xyz"),
        ("openai dot com and anthropic dot com", "openai.com and anthropic.com"),
        ("grab it from cdn dot example dot net", "grab it from cdn.example.net"),
        ("ship it to ops at gov dot gov", "ship it to ops at gov.gov"),
        ("another new line of code", "another new line of code"),
        ("new line hello", "hello"),
        ("hello new line", "hello"),
        ("hello new paragraph", "hello"),
        ("we opened a new paragraph in the doc", "we opened a new paragraph in the doc"),
        ("the new line that we drew", "the new line that we drew"),
        ("add one new line and one new paragraph", "add one new line and one new paragraph"),
        ("is this working question mark ", "is this working?"),
        ("wow exclamation point.", "wow!"),
        ("that is all full stop", "that is all."),
        ("period", "period"),
        ("say it question mark now", "say it question mark now"),
        ("it's three no wait four", "it's four"),
        ("meet at three, no wait, four pm", "meet at four pm"),
        ("scratch that", ""),
        ("first scratch that second scratch that third", "third"),
        ("go to the the store", "go to the store"),
        ("we need to to to fix it", "we need to fix it"),
        ("I said that that was fine", "I said that that was fine"),
        ("he had had enough", "he had had enough"),
        ("send it to Bob no wait to Alice", "send it to Alice"),
        ("  ", ""),
        ("\n\n\n", ""),
        ("a\n\n\n\n\nb", "a\n\nb"),
        ("hello\t\tworld", "hello world"),
        ("one  ,  two  .  three", "one, two. three"),
        ("trailing space \n", "trailing space"),
        ("tabs\tand   spaces", "tabs\tand spaces"),
        ("hello ; world : again ! yes ?", "hello; world: again! yes?"),
        ("line one\n   \nline two", "line one\n\nline two"),
        ("MiXeD CaSe StAyS", "MiXeD CaSe StAyS"),
        ("digits 123 456 stay", "digits 123 456 stay"),
        ("unicode café naïve résumé", "unicode café naïve résumé"),
        ("emoji 🎉 stays put", "emoji 🎉 stays put"),
        ("um so I pushed the fix to production no wait to staging", "so I pushed the fix to staging"),
        ("uh email me at first dot last at gmail dot com question mark", "email me at first.last@gmail.com?"),
        ("visit example dot com new line then uh call me", "visit example.com\nthen call me"),
        ("um scratch that go to github dot io", "go to github.io"),
    ]

    static let fillerOff: [(raw: String, expected: String)] = [
        ("um hello", "um hello"),
        ("um so I think uh we should go", "um so I think uh we should go"),
        ("the museum was empty", "the museum was empty"),
        ("uh, let's start", "uh, let's start"),
    ]

    static let ensurePeriod: [(raw: String, expected: String)] = [
        ("this is a sentence", "this is a sentence."),
        ("already done!", "already done!"),
        ("ends with colon:", "ends with colon:"),
        ("are you coming question mark", "are you coming?"),
        ("", ""),
        ("um", ""),
        ("hello new paragraph world", "hello\n\nworld."),
    ]

    static let leadingAlways: [(raw: String, expected: String)] = [
        ("appended", " appended"),
        ("  padded", " padded"),
        ("um hello", " hello"),
        ("", ""),
    ]

    static let leadingNever: [(raw: String, expected: String)] = [
        ("appended", "appended"),
        ("  padded", "padded"),
        ("um hello", "hello"),
        ("", ""),
    ]

    static let leadingAlwaysPeriod: [(raw: String, expected: String)] = [
        ("chained options here", " chained options here."),
    ]

    static let dictionary: [(raw: String, expected: String)] = [
        ("i deployed to in forge today", "i deployed to InsForge today"),
        ("switching from whisper flow", "switching from Wispr Flow"),
        ("using insforge here", "using InsForge here"),
        ("an old clodhopper", "an old clodhopper"),
        ("clod said hello", "Claude said hello"),
        ("we run post   grass   sequel in prod", "we run PostgreSQL in prod"),
        ("um so I pushed the fix to in forge no wait to production", "so I pushed the fix to production"),
        ("ins forge and in forge and INSFORGE", "InsForge and InsForge and InsForge"),
        ("wispr flow versus whisper flow", "Wispr Flow versus Wispr Flow"),
        ("email insforge at gmail dot com", "email InsForge@gmail.com"),
    ]

}
