import XCTest
@testable import WispritPersistence

/// The JSON layer exists only to be byte-compatible with CPython's `json`
/// module for the two files Wisprit shares across the Python and Swift eras
/// (config.json, metrics.log). These tests pin the places the two could drift.
final class JSONTests: XCTestCase {

    private func reserialize(_ text: String) throws -> String {
        WispritJSON.serializeCompact(try WispritJSON.parse(text))
    }

    func testObjectKeyOrderIsPreserved() throws {
        let text = #"{"zebra": 1, "alpha": 2, "middle": 3}"#
        XCTAssertEqual(try reserialize(text), text)
    }

    func testIntStaysIntAndFloatStaysFloat() throws {
        XCTAssertEqual(try reserialize(#"{"a": 1000, "b": 2.5, "c": -3, "d": 1e3}"#),
                       #"{"a": 1000, "b": 2.5, "c": -3, "d": 1000.0}"#)
    }

    func testSeparatorsMatchPythonDefaults() throws {
        XCTAssertEqual(try reserialize(#"{"a":[1,2],"b":{}}"#), #"{"a": [1, 2], "b": {}}"#)
    }

    func testPrettyPrintMatchesIndentTwo() throws {
        let value = try WispritJSON.parse(#"{"a": [1, {"b": null}], "c": []}"#)
        XCTAssertEqual(WispritJSON.serializePretty(value), """
        {
          "a": [
            1,
            {
              "b": null
            }
          ],
          "c": []
        }
        """)
    }

    /// `ensure_ascii=False` + Python's escape table: only `"`, `\` and C0
    /// controls are escaped; `/`, DEL and non-ASCII stay raw.
    func testStringEscapingMatchesEnsureAsciiFalse() {
        XCTAssertEqual(WispritJSON.quote("a/b"), "\"a/b\"")
        XCTAssertEqual(WispritJSON.quote("é—😀"), "\"é—😀\"")
        XCTAssertEqual(WispritJSON.quote("q\"b\\s"), #""q\"b\\s""#)
        XCTAssertEqual(WispritJSON.quote("\n\r\t\u{08}\u{0C}"), #""\n\r\t\b\f""#)
        XCTAssertEqual(WispritJSON.quote("\u{01}\u{1F}"), "\"\\u0001\\u001f\"")
        XCTAssertEqual(WispritJSON.quote("\u{7F}"), "\"\u{7F}\"")
    }

    func testEscapeSequencesParseBack() throws {
        guard case .object(let object) =
            try WispritJSON.parse(#"{"k": "aé\/\t\"\\ 😀"}"#) else {
            return XCTFail("not an object")
        }
        XCTAssertEqual(object["k"], .string("aé/\t\"\\ 😀"))
    }

    func testFloatReprMatchesPythonRepr() {
        // Generated by: [repr(x) for x in ...] under the repo venv python.
        XCTAssertEqual(WispritJSON.pythonRepr(1785871825.3455071), "1785871825.3455071")
        XCTAssertEqual(WispritJSON.pythonRepr(1.0), "1.0")
        XCTAssertEqual(WispritJSON.pythonRepr(0.1), "0.1")
        XCTAssertEqual(WispritJSON.pythonRepr(-3.0), "-3.0")
        XCTAssertEqual(WispritJSON.pythonRepr(1e16), "1e+16")
        XCTAssertEqual(WispritJSON.pythonRepr(1e-05), "1e-05")
        XCTAssertEqual(WispritJSON.pythonRepr(438343.0), "438343.0")
        XCTAssertEqual(WispritJSON.pythonRepr(3171.2), "3171.2")
    }

    func testMalformedInputThrows() {
        XCTAssertThrowsError(try WispritJSON.parse("{not json"))
        XCTAssertThrowsError(try WispritJSON.parse("{\"a\": 1,}"))
        XCTAssertThrowsError(try WispritJSON.parse("[1, 2] junk"))
        XCTAssertThrowsError(try WispritJSON.parse(""))
        XCTAssertThrowsError(try WispritJSON.parse("{\"a\": tru}"))
    }

    func testJSONObjectUpdateKeepsOriginalSlot() {
        var object = JSONObject([("a", .int(1)), ("b", .int(2))])
        object["a"] = .int(9)
        object["c"] = .int(3)
        XCTAssertEqual(object.keys, ["a", "b", "c"])
        object["b"] = nil
        XCTAssertEqual(object.keys, ["a", "c"])
    }

    func testMergeMatchesPythonDictUpdate() {
        var base = JSONObject([("x", .int(1)), ("y", .int(2))])
        base.merge(JSONObject([("y", .int(20)), ("z", .int(30))]))
        XCTAssertEqual(base.keys, ["x", "y", "z"])
        XCTAssertEqual(base["y"], .int(20))
    }

    func testDeeplyNestedUnknownValueRoundTrips() throws {
        let text = #"{"future": {"a": [{"b": [1, 2.5, null, true, false, "s"]}]}}"#
        XCTAssertEqual(try reserialize(text), text)
    }
}
