// swift-tools-version: 6.0
// Native Wisprit — one shared core, thin platform shells.
// Structure is contractual: see docs/SWIFT-INTERFACES.md. Build agents do NOT edit this file.
import PackageDescription

let v5: [SwiftSetting] = [.swiftLanguageMode(.v5)]

let package = Package(
    name: "Wisprit",
    platforms: [.macOS("26.0"), .iOS("26.0")],
    products: [
        .library(name: "WispritKit", targets: ["WispritKit"]),
        .library(name: "WispritCore", targets: [
            "WispritKit", "WispritPostProcess", "WispritDictionary",
            "WispritCorrections", "WispritPersistence", "WispritRefine", "WispritEngine",
        ]),
    ],
    targets: [
        // Shared foundation — owned by the orchestrator, frozen for agents.
        .target(name: "WispritKit", swiftSettings: v5),

        // One target per build agent; cross-module coupling only through WispritKit.
        .target(name: "WispritPostProcess", dependencies: ["WispritKit"], swiftSettings: v5),
        .target(name: "WispritDictionary", dependencies: ["WispritKit"], swiftSettings: v5),
        .target(name: "WispritCorrections", dependencies: ["WispritKit"], swiftSettings: v5),
        .target(name: "WispritPersistence", dependencies: ["WispritKit"], swiftSettings: v5),
        .target(name: "WispritRefine", dependencies: ["WispritKit"], swiftSettings: v5),
        .target(name: "WispritEngine", dependencies: ["WispritKit"], swiftSettings: v5),
        // Accuracy measurement: WER/CER/term-recall scoring, corpus model, scoreboard,
        // refine battery cases. Pure — no audio, no models, no network.
        .target(name: "WispritEval", dependencies: ["WispritKit"], swiftSettings: v5),

        // Apple Intelligence polish modes (replaces the Python claude-CLI polish; on-device only).
        .target(name: "WispritPolish", dependencies: ["WispritKit", "WispritRefine"], swiftSettings: v5),
        // XPC contract between the main app and the palette input method.
        .target(name: "WispritIMProtocol", dependencies: ["WispritKit"], swiftSettings: v5),
        // The palette input method (live in-field streaming tier). Own .app bundle.
        .executableTarget(name: "WispritIM", dependencies: ["WispritKit", "WispritIMProtocol"], swiftSettings: v5),

        // macOS shell (Developer ID SKU). Not iOS-buildable by design.
        .target(name: "WispritMacInput", dependencies: ["WispritKit"], swiftSettings: v5),
        .target(name: "WispritMacUI", dependencies: ["WispritKit"], swiftSettings: v5),
        .executableTarget(
            name: "WispritMac",
            dependencies: [
                "WispritKit", "WispritPostProcess", "WispritDictionary", "WispritCorrections",
                "WispritPersistence", "WispritRefine", "WispritEngine", "WispritEval",
                "WispritMacInput", "WispritMacUI", "WispritPolish", "WispritIMProtocol",
            ],
            swiftSettings: v5),

        // Explicit lowercase paths: the repo's Python tests/ dir and SPM's Tests/
        // are one directory on case-insensitive APFS; git records lowercase.
        .testTarget(name: "WispritPostProcessTests", dependencies: ["WispritPostProcess", "WispritDictionary"], path: "tests/WispritPostProcessTests", swiftSettings: v5),
        .testTarget(name: "WispritDictionaryTests", dependencies: ["WispritDictionary"], path: "tests/WispritDictionaryTests", swiftSettings: v5),
        .testTarget(name: "WispritCorrectionsTests", dependencies: ["WispritCorrections"], path: "tests/WispritCorrectionsTests", swiftSettings: v5),
        .testTarget(name: "WispritPersistenceTests", dependencies: ["WispritPersistence"], path: "tests/WispritPersistenceTests", swiftSettings: v5),
        .testTarget(name: "WispritRefineTests", dependencies: ["WispritRefine", "WispritEval"], path: "tests/WispritRefineTests", swiftSettings: v5),
        .testTarget(name: "WispritEvalTests", dependencies: ["WispritEval"], path: "tests/WispritEvalTests", swiftSettings: v5),
        .testTarget(name: "WispritEngineTests", dependencies: ["WispritEngine"], path: "tests/WispritEngineTests", swiftSettings: v5),
        .testTarget(name: "WispritMacInputTests", dependencies: ["WispritMacInput"], path: "tests/WispritMacInputTests", swiftSettings: v5),
        .testTarget(name: "WispritMacUITests", dependencies: ["WispritMacUI"], path: "tests/WispritMacUITests", swiftSettings: v5),
        .testTarget(name: "WispritMacTests", dependencies: ["WispritMac"], path: "tests/WispritMacTests", swiftSettings: v5),
        .testTarget(name: "WispritPolishTests", dependencies: ["WispritPolish"], path: "tests/WispritPolishTests", swiftSettings: v5),
        .testTarget(name: "WispritIMTests", dependencies: ["WispritIM", "WispritIMProtocol"], path: "tests/WispritIMTests", swiftSettings: v5),
    ]
)
