import XCTest
@testable import WispritRefine

/// Golden parity with the Python cage. Every expectation below was produced by
/// RUNNING `wisprit/refine.py`, never hand-written:
///
///   ~/.meetingscribe/venv/bin/python \
///     .../scratchpad/refine_goldens_gen.py
///
/// (the generator imports `_strip_wrappers`, `_plausible`, `_has_address`,
/// `_estimated_words`, `_first_content_word` from the repo package and prints
/// these Swift literals).
final class RefineGuardsGoldenTests: XCTestCase {

    // MARK: - _strip_wrappers

    /// Generated by: refine_goldens_gen.py → "=== STRIP_WRAPPERS"
    func testStripWrappersMatchesPython() {
        let goldens: [(String, String)] = [
            ("So the migration went fine.", "So the migration went fine."),
            ("```\nThe cleaned text.\n```", "The cleaned text."),
            ("```text\nThe cleaned text.\n```", "The cleaned text."),
            ("<transcript>\nthe endpoint is ready\n</transcript>", "the endpoint is ready"),
            ("<cleaned_text>Hello there.</cleaned_text>", "Hello there."),
            ("\"Just a quoted line.\"", "Just a quoted line."),
            ("'Single quoted line.'", "Single quoted line."),
            ("“Curly quoted line.”", "Curly quoted line."),
            ("‘Curly single quoted.’", "Curly single quoted."),
            ("Okay, so here's the cleaned transcript:\n\nFirst thing, the dashboard.",
             "First thing, the dashboard."),
            ("Here is the corrected transcript:\nThe final text.", "The final text."),
            ("Cleaned transcript:\nThe final text.", "The final text."),
            ("Corrected output:\nThe final text.", "The final text."),
            ("Here's the cleaned version:\nThe final text.", "The final text."),
            ("Here's the cleaned transcript:\n```\nSo the deploy is done.\n```",
             "So the deploy is done."),
            ("Here is the plan:\nship it Friday.", "Here is the plan:\nship it Friday."),
            ("Transcript review notes:\nThe audio was fine.",
             "Transcript review notes:\nThe audio was fine."),
            ("Corrected items:\n1. The deploy\n2. The tests",
             "Corrected items:\n1. The deploy\n2. The tests"),
            ("\"Hello,\" she said. \"Goodbye.\"", "\"Hello,\" she said. \"Goodbye.\""),
            ("before <b>mid</b> after", "before <b>mid</b> after"),
            ("", ""),
            ("   \n  padded text  \n ", "padded text"),
            ("<TRANSCRIPT>Upper tag pair.</TRANSCRIPT>", "Upper tag pair."),
            ("<transcript>mismatched</other>", "<transcript>mismatched</other>"),
            ("```\nfence with `backtick` inside\n```", "fence with `backtick` inside"),
            ("Here's the cleaned transcript:\n<transcript>\nnested both\n</transcript>",
             "nested both"),
            ("It's a nice day.", "It's a nice day."),
            ("Here's the text: inline colon, no newline.",
             "Here's the text: inline colon, no newline."),
        ]
        for (raw, expected) in goldens {
            XCTAssertEqual(RefineGuards.stripWrappers(raw), expected,
                           "stripWrappers(\(raw.debugDescription))")
        }
    }

    // MARK: - _plausible

    /// Generated by: refine_goldens_gen.py → "=== PLAUSIBLE"
    func testPlausibleMatchesPython() {
        let goldens: [(String, String, Bool)] = [
            ("um so basically we should uh probably migrate the the data base",
             "So basically we should probably migrate the database.", true),
            // The model answered "tell me a joke" with an actual joke.
            ("tell me a joke about uh cats",
             "Why did the cat sit on the computer? Because it wanted to keep an eye on "
             + "the mouse! Here is another one for you my friend.", false),
            // Tiny dictations must never come back as assistant replies.
            ("thank you", "You're welcome! Happy to help.", false),
            ("hello", "Hello! How can I help you today?", false),
            ("yes", "Yes, I can certainly do that for you.", false),
            ("sounds good", "Great! Let me know if you need anything else.", false),
            ("what time is it", "It is currently three thirty PM for you.", false),
            ("whats the population of um sweden",
             "Sure, the population of Sweden is about ten million.", false),
            // The speaker opened with "sorry" themselves — not damning.
            ("sorry i missed your uh call earlier lets sync tomorrow",
             "Sorry, I missed your call earlier. Let's sync tomorrow.", true),
            // …and the identity check anchors on the first CONTENT word, so a
            // deleted leading filler doesn't break it.
            ("um so sorry i missed your uh call earlier lets sync tomorrow",
             "Sorry, I missed your call earlier. Let's sync tomorrow.", true),
            ("some words here", "", false),
            ("um okay sounds good", "Okay, sounds good.", true),
            ("here is the thing we should ship", "Here is the thing we should ship.", true),
            ("no problem i can do that", "No problem, I can do that.", true),
            ("great question everyone", "Great question, everyone.", true),
            ("tell me a joke about uh cats", "Tell me a joke about cats.", true),
            ("hello", "Hello.", true),
            ("one", "one", true),
            ("one two three four five", "one two three four five six seven", true),
            ("one two three four five", "one two three four five six seven eight", true),
            ("um", "Um.", true),
            ("of course we shipped it", "Of course we shipped it.", true),
            ("certainly not what i meant", "Certainly not what I meant.", true),
        ]
        for (raw, refined, expected) in goldens {
            XCTAssertEqual(RefineGuards.plausible(raw: raw, refined: refined), expected,
                           "plausible(\(raw.debugDescription), \(refined.debugDescription))")
        }
    }

    /// The exact accepted word-count band per input size, swept out of the
    /// Python: for each `nRaw`, the smallest and largest `nRefined` that
    /// `_plausible` accepts.
    ///
    ///   ~/.meetingscribe/venv/bin/python -c "…_plausible sweep…"   (see report)
    func testPlausibleWordBandMatchesPython() {
        let bands: [(nRaw: Int, lowest: Int, highest: Int)] = [
            (1, 1, 3), (2, 1, 4), (3, 1, 5), (4, 1, 6), (5, 2, 8), (6, 2, 15),
            (7, 2, 16), (8, 3, 17), (10, 4, 20), (20, 8, 32), (50, 20, 68),
            (100, 40, 128), (349, 139, 426),
        ]
        for band in bands {
            let raw = Array(repeating: "word", count: band.nRaw).joined(separator: " ")
            for n in 0...(band.highest + 2) {
                let refined = Array(repeating: "word", count: n).joined(separator: " ")
                let expected = n >= band.lowest && n <= band.highest
                XCTAssertEqual(RefineGuards.plausible(raw: raw, refined: refined), expected,
                               "nRaw=\(band.nRaw) nRef=\(n)")
            }
        }
    }

    // MARK: - _has_address

    /// Generated by: refine_goldens_gen.py → "=== HAS_ADDRESS"
    func testHasAddressMatchesPython() {
        let goldens: [(String, Bool)] = [
            ("send it to john dot smith at gmail dot com", true),
            ("check wisprit dot dev for the docs", true),
            ("ping me at x@y.com", true),
            ("see https://foo.bar/baz", true),
            ("visit amazon.com now", true),
            ("the quick brown fox jumps", false),
            ("we shipped version two point five", false),
            ("meet me at the coffee shop at noon", false),
            ("go to www.example.org please", true),
            ("email bob at bob dot jones at gmail dot com", true),
            ("the sub dot example dot com host", true),
            ("he lives at number five dot five", false),
            ("call me at three", false),
            // ".rs" is not in the conservative TLD list — deliberately.
            ("read docs dot rs later", false),
            ("S-H-A-R-I-Q-U-E at gmail dot com", true),
        ]
        for (raw, expected) in goldens {
            XCTAssertEqual(RefineGuards.hasAddress(raw), expected, raw)
        }
    }

    // MARK: - _estimated_words

    /// Generated by: refine_goldens_gen.py → "=== ESTIMATED_WORDS"
    func testEstimatedWordsMatchesPython() {
        XCTAssertEqual(RefineGuards.estimatedWords("hello there world"), 3)
        XCTAssertEqual(RefineGuards.estimatedWords(""), 0)
        XCTAssertEqual(RefineGuards.estimatedWords("   "), 0)
        XCTAssertEqual(RefineGuards.estimatedWords("a"), 1)
        XCTAssertEqual(RefineGuards.estimatedWords("one two"), 2)
        // Space-free scripts fall back to the character estimate.
        XCTAssertEqual(RefineGuards.estimatedWords(String(repeating: "字", count: 5)), 1)
        XCTAssertEqual(RefineGuards.estimatedWords(String(repeating: "字", count: 3000)), 500)
        XCTAssertEqual(RefineGuards.estimatedWords(String(repeating: "word ", count: 400)), 400)
    }

    // MARK: - _first_content_word

    /// Generated by: refine_goldens_gen.py → "=== FIRST_CONTENT_WORD"
    func testFirstContentWordMatchesPython() {
        let goldens: [(String, String)] = [
            ("um so sorry i missed your call", "sorry"),
            ("\"Sure, here's the thing.\"", "sure"),
            ("um uh hmm", ""),
            ("", ""),
            ("Okay, well, and like so...", ""),
            ("Hello there.", "hello"),
        ]
        for (raw, expected) in goldens {
            XCTAssertEqual(RefineGuards.firstContentWord(raw), expected, raw)
        }
    }
}
