import XCTest
@testable import WispritEngine

/// Golden parity with `wisprit/asr_batch.py::_drop_if_hallucinated`.
///
/// Generated by running the real Python:
///
///   ~/.meetingscribe/venv/bin/python -c '
///   import sys; sys.path.insert(0,"."); import logging; logging.disable(logging.CRITICAL)
///   from wisprit.asr_batch import _drop_if_hallucinated, _HALLUCINATIONS
///   for c in CASES: print(repr(c), "->", repr(_drop_if_hallucinated(c)))
///   print(sorted(_HALLUCINATIONS))'
///
/// Do not hand-edit the expectations.
final class SilenceHallucinationTests: XCTestCase {

    private static let goldens: [(String, String)] = [
        ("Thank you.", ""),
        ("thank you", ""),
        ("THANK YOU.", ""),
        ("  Thank you.  ", ""),
        ("Thanks for watching!", ""),
        ("Thank you for watching", ""),
        ("Thank you very much.", ""),
        ("you", ""),
        ("You.", ""),
        (".", ""),
        ("bye", ""),
        ("Bye!", ""),
        ("please subscribe", ""),
        ("So", ""),
        ("so.", ""),
        ("Okay", ""),
        ("okay.", ""),
        ("I'm sorry", ""),
        ("i'm sorry.", ""),
        ("Subtitles by the amara.org community", ""),
        ("Thanks", ""),
        ("thanks.", ""),
        ("Thank you.Thank you.", ""),
        ("\u{443}ou", ""),                       // Cyrillic 'у' + "ou"
        ("Thank you for the coffee this morning", "Thank you for the coffee this morning"),
        ("Thank you, Sharique.", "Thank you, Sharique."),
        ("Bye for now", "Bye for now"),
        ("So I was thinking we should ship it.", "So I was thinking we should ship it."),
        ("Okay, let's go.", "Okay, let's go."),
        ("You are right.", "You are right."),
        ("", ""),
        ("   ", "   "),                          // Python returns `text`, NOT the stripped form
        ("Thanks for watching the demo", "Thanks for watching the demo"),
        ("thank  you", "thank  you"),            // doubled space is not a member
        ("Thank you!", "Thank you!"),            // "thank you!" is not in the set
    ]

    /// Exactly the 27 members of `_HALLUCINATIONS`, sorted, from the same run.
    private static let goldenPhrases = [
        ".", "bye", "bye!", "bye.", "i'm sorry", "i'm sorry.", "okay", "okay.",
        "please subscribe", "so", "so.", "subtitles by the amara.org community",
        "thank you", "thank you for watching", "thank you for watching.",
        "thank you very much", "thank you very much.", "thank you.",
        "thank you.thank you.", "thanks", "thanks for watching",
        "thanks for watching!", "thanks for watching.", "thanks.", "you", "you.",
        "\u{443}ou",
    ]

    func testGoldenParityWithPython() {
        for (input, expected) in Self.goldens {
            XCTAssertEqual(SilenceHallucinationFilter.drop(input), expected,
                           "input \(String(reflecting: input))")
        }
    }

    func testPhraseSetMatchesPython() {
        XCTAssertEqual(SilenceHallucinationFilter.phrases.sorted(), Self.goldenPhrases)
        XCTAssertEqual(SilenceHallucinationFilter.phrases.count, 27)
    }

    func testFilterWrapsBatchEngineAndSuppressesHallucination() async {
        let batch = FilteredBatchTranscriber(FixedBatch(text: "Thank you."))
        let out = await batch.transcribe(pcm: Data([1, 2, 3, 4]), settings: AsrSettings())
        XCTAssertNil(out, "a whole-output hallucination must not reach the insert path")
    }

    func testFilterKeepsRealSentenceContainingThankYou() async {
        let batch = FilteredBatchTranscriber(FixedBatch(text: "  Thank you for the coffee this morning  "))
        let out = await batch.transcribe(pcm: Data([1, 2, 3, 4]), settings: AsrSettings())
        XCTAssertEqual(out, "Thank you for the coffee this morning")
    }

    func testWhisperKitSlotIsStillAStub() async {
        let out = await WhisperKitBatchStub().transcribe(pcm: Data([1, 2]), settings: AsrSettings())
        XCTAssertNil(out, "Phase 3 slot must stay inert, never invent text")
    }
}

struct FixedBatch: BatchTranscribing {
    let name = "fixed"
    let text: String?
    func transcribe(pcm: Data, settings: AsrSettings) async -> String? { text }
}
